language: scala
dist: xenial

jdk: openjdk11

scala:
  - 2.13.1

sbt_args: -J-Xms1024M -J-Xmx2200M -J-Xss8M

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - |
    mkdir -p cache_ignore/assemblyOption
    mkdir -p cache_ignore/assembly
    if [ -f ./target/streams/\$global/assemblyOption ]; then
      mv ./target/streams/\$global/assemblyOption cache_ignore/assemblyOption/$PROJECT
    fi
    if [ -f ./target/streams/\$global/assembly ]; then
       mv ./target/streams/\$global/assembly cache_ignore/assembly/$PROJECT
    fi

cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.sbt"
  - "$HOME/.ivy2/cache"
  - "$HOME/docker"
  - "$HOME/.docker"
  - "./target"

branches:
  only:
  - master

jobs:
  include:
  - stage: test
    script: sbt ++$TRAVIS_SCALA_VERSION test
    if: type = pull_request

  - stage: build and push api docker image
    script: make docker-login && sbt ++$TRAVIS_SCALA_VERSION moonlight-api/dockerBuildAndPush
    if: type != pull_request && branch = master
    env:
      # DOCKERHUB_USERNAME
      - secure: "ZfLp5JP40GPnzkucWJswlsaeZFVa4Vm47LnjAufqYceKnv+X7FyT99wW2+3MXccF53u7hSiS6pAL8eLan5lqg2mzKUmsp6Xv0NefbOrJHD1vVl7iDpeh8cMLYX4QwHCMrDE5SFBQ7FWMBbtg+bxX+FBJhczjbMrD7MtwhViTokVPFDkAfqazvCGkUsrn+oQwcRfL+b803VzunUjAfhsraMWpAPAEb1k3Oog7YqDeXeg7dBxOheGrbNEHfKnO8B1/X9+GfeQFZT/vOHcKGQNqrexZb6jDEeHojVumC3x9Z/LZjdCwXw0Xb+jXWGVyrMi77oAisCOu8CvfkaHgs7nthd2LoB1GuT1GElGLMsd2UI/YKX0+tNqn3QnT981ENcI3zevuKSqpipM+RfT/Rf56eo2gXkXH+KYm8UtKUEI4Rhc83qwqftxizgoZZMEMlqCt1rdYjVhBoODAwCeILL7VWv3hmXgS8H8U1K2EqOKbfTXXXpEfDZV/jlcwulFXcXamHExqpJ7OqecphXXzzs2/2KDLpQ9KC6YI776xxpnRG6JM/YzxN7PKo9hchaXtk2DXBvEQzYahmER9QrNDWB96OJTAr4Wxgg1Pd/2W0tzChAo/C6l6BT+Ftk2s1EMBh+VECZ8+sTh0RUuFaEp/7o0kyHjx5IqzoopGw2Yqw3TjxTo="
      # DOCKERHUB_PASSWORD
      - secure: "M8iE7WYYPvp2LqmW8HIEvX4zuRQ36tywxhRbI8ER8toJ8TmaRfdLsR8D2u5M8G+TVHVt2EzSlVdWfOByJv7QGwMuTzvBNljw3eFkkcevcVpQ6Z7thH7ZK0TN1LUaKyWWvG3464scn9t8Nyt7MGXc+IrXqKTk1pQ2D3rDDZDL/7BOHi457RZ67FRIyzLHbr4wx5x/QSMJ9gMTF2JSUoCXeDlc1ojEHJe2h9ImX3m+0DH049kOSzkyhNHenxDqYE2+PpgD9VDmJomguz2P0UsUIvNqA84c0RLXGuazhUJK3QUMDdIvVRhQ3/sZC//kCD6x6dYtIAXxF07LddtywDTNbHBl3dE7S3YsH1i1N5W/o72EAmJmFJHqQ/rKB3ZwOWlRTTG/8Qx+cm1Al17qBMPcgmTKzFDy4TnNu27r27UumJNerHc5hZ3ieKGs6o4c+yhF4WyqCptK/5GoijN1CxzcmG/J/DjbRVCiAUCPRh6iPgqXu6Phcf/EqscT+C2z3LGPZkUvqERfssQV2lyuQAvIWu8t8cdd/kg9j1W/t8gAHYkpXWH4+qyl3CMAdmgcbCebaqB0Plww18ou70cMl9lnyBR98euLfFG0/gbNQM3EWQsL0HTlQGmkNcsPpb1cU8/qpXAtZH/+rrc9ApSRLzB7njCL/QrOv9Zokb4TaH0URWE="
